name: Python List

on: [push, pull_request]

jobs:
  python-lint:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        working-directory: sols/python
        run: |
          python -m pip install --upgrade poetry
          poetry install
      - name: Lint
        working-directory: sols/python
        run: poetry run pre-commit run --all-files --show-diff-on-failure